// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cleanup():Promise<void>;

export function CopySelection():Promise<Array<number>>;

export function FindNext(arg1:Array<number>,arg2:number):Promise<number>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFileWithData(arg1:string,arg2:Array<number>):Promise<void>;

export function PasteBytes(arg1:number,arg2:Array<number>):Promise<void>;

export function ReadPage(arg1:number):Promise<Array<number>>;

export function Redo():Promise<void>;

export function Replace(arg1:number,arg2:Array<number>,arg3:Array<number>):Promise<void>;

export function SaveFile():Promise<void>;

export function Search(arg1:Array<number>,arg2:number):Promise<Array<number>>;

export function Undo():Promise<void>;

export function WriteByte(arg1:number,arg2:number):Promise<void>;

export function WriteBytesBuffered(arg1:number,arg2:Array<number>):Promise<void>;

export function WriteBytesWithBackup(arg1:number,arg2:Array<number>):Promise<void>;
