// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cleanup() {
  return window['go']['main']['HexEditor']['Cleanup']();
}

export function CopySelection() {
  return window['go']['main']['HexEditor']['CopySelection']();
}

export function FindNext(arg1, arg2) {
  return window['go']['main']['HexEditor']['FindNext'](arg1, arg2);
}

export function OpenFile(arg1) {
  return window['go']['main']['HexEditor']['OpenFile'](arg1);
}

export function OpenFileWithData(arg1, arg2) {
  return window['go']['main']['HexEditor']['OpenFileWithData'](arg1, arg2);
}

export function PasteBytes(arg1, arg2) {
  return window['go']['main']['HexEditor']['PasteBytes'](arg1, arg2);
}

export function ReadPage(arg1) {
  return window['go']['main']['HexEditor']['ReadPage'](arg1);
}

export function Redo() {
  return window['go']['main']['HexEditor']['Redo']();
}

export function Replace(arg1, arg2, arg3) {
  return window['go']['main']['HexEditor']['Replace'](arg1, arg2, arg3);
}

export function SaveFile() {
  return window['go']['main']['HexEditor']['SaveFile']();
}

export function Search(arg1, arg2) {
  return window['go']['main']['HexEditor']['Search'](arg1, arg2);
}

export function Undo() {
  return window['go']['main']['HexEditor']['Undo']();
}

export function WriteByte(arg1, arg2) {
  return window['go']['main']['HexEditor']['WriteByte'](arg1, arg2);
}

export function WriteBytesBuffered(arg1, arg2) {
  return window['go']['main']['HexEditor']['WriteBytesBuffered'](arg1, arg2);
}

export function WriteBytesWithBackup(arg1, arg2) {
  return window['go']['main']['HexEditor']['WriteBytesWithBackup'](arg1, arg2);
}
